### ISSUE TITLE
Error when importing: from af2seq import GradientDesign

### ISSUE THREAD

**Issue by linamp** [bene837/af2seq#1]
I just installed af2seq and I am getting this error:

---> 20 from af2seq.alphafold.common import residue_constants
     21 from af2seq.alphafold.data import parsers
     22 from matplotlib import pyplot as plt

File [~/miniconda3/envs/myenv_gl/envs/af2seq/lib/python3.8/site-packages/af2seq/alphafold/common/residue_constants.py:775](https://vscode-remote+ssh-002dremote-002bgreatlakes.vscode-resource.vscode-cdn.net/home/linamp/Documents/af2seq/notebooks/~/miniconda3/envs/myenv_gl/envs/af2seq/lib/python3.8/site-packages/af2seq/alphafold/common/residue_constants.py:775)
...

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by linamp** [comment]
Looks like there are several deprecations that are affecting the program: np.int need to be int, np.object needs to be object.

**Comment by Navid-visual** [comment]
Try to downgrade Numpy to version 1.19.5. In general try to install the specified version of the packages.
name: af2seq
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - absl-py=0.13.0
  - biopython=1.78
  - chex=0.1.0
  - dm-haiku=0.0.5
  - dm-tree=0.1.6
  - immutabledict=2.0.0
  - jax=0.2.27
  - numpy=1.19.5
  - pandas=1.3.4
  - scipy=1.7.0
  - tensorflow-cpu=2
  - ca-certificates
  - certifi
  - openssl
  - pip=21.2.4
  - optax=0.1.0
  - tqdm
  - matplotlib
  - seaborn
  - py3dmol
  - pymol-open-source
  - pdbfixer
  - openmm=7.5.1
  - pip:
    - contextlib2==21.6.0
    - iminuit==1.5.4
    - ml-collections==0.1.0
    - pyyaml==6.0
    - tmscoring==0.4.post0

**Comment by Navid-visual** [comment]
Start with installing the packages with unspecified versions and continue with the ones with a version number. Try to use conda whenever possible as it takes the confilicts into account and downgrades other packages when necessary.
